SELECT [SalesOrderID]
      ,[OrderDate]
      ,[DueDate]
      ,[ShipDate]
      ,[Status]
      ,[OnlineOrderFlag]
      ,[SalesOrderNumber]
      ,[PurchaseOrderNumber]
      ,[AccountNumber]
      ,[CustomerID]
      ,[ShipToAddressID]
      ,[BillToAddressID]
      ,[ShipMethod]
      ,[SubTotal]
      ,[TaxAmt]
      ,[TotalDue]
  FROM {{source('adventure_works', 'SalesOrderHeader')}} 