version: 2

models:
  - name: stg_sales_detail
    description: "Sales Order Detail"
    columns:
      - name: SalesOrderDetailID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null